// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACanZYJ-0xc_zLZadmI43b7i1rTW4-eBI',
    appId: '1:697339966383:web:27e1f60fecbb24536bb55a',
    messagingSenderId: '697339966383',
    projectId: 'mr-and-mrs-genz-outfit',
    authDomain: 'mr-and-mrs-genz-outfit.firebaseapp.com',
    storageBucket: 'mr-and-mrs-genz-outfit.firebasestorage.app',
    measurementId: 'G-ZTE5DEE1K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdRFRDy6mDPXZn0Tgk5luEO4KoFilmj4g',
    appId: '1:697339966383:android:b951864acb1e18866bb55a',
    messagingSenderId: '697339966383',
    projectId: 'mr-and-mrs-genz-outfit',
    storageBucket: 'mr-and-mrs-genz-outfit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg6LWIbuO9fwtuYkMdeYno_mv66WWLHDs',
    appId: '1:697339966383:ios:e6ecc99394e44e7d6bb55a',
    messagingSenderId: '697339966383',
    projectId: 'mr-and-mrs-genz-outfit',
    storageBucket: 'mr-and-mrs-genz-outfit.firebasestorage.app',
    iosBundleId: 'com.example.mrAndMrsGenzOutfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg6LWIbuO9fwtuYkMdeYno_mv66WWLHDs',
    appId: '1:697339966383:ios:e6ecc99394e44e7d6bb55a',
    messagingSenderId: '697339966383',
    projectId: 'mr-and-mrs-genz-outfit',
    storageBucket: 'mr-and-mrs-genz-outfit.firebasestorage.app',
    iosBundleId: 'com.example.mrAndMrsGenzOutfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACanZYJ-0xc_zLZadmI43b7i1rTW4-eBI',
    appId: '1:697339966383:web:31eb19ace7b5d1566bb55a',
    messagingSenderId: '697339966383',
    projectId: 'mr-and-mrs-genz-outfit',
    authDomain: 'mr-and-mrs-genz-outfit.firebaseapp.com',
    storageBucket: 'mr-and-mrs-genz-outfit.firebasestorage.app',
    measurementId: 'G-LQ88CXH11G',
  );
}
