import 'package:flutter/material.dart';

import '../models/product_model.dart';
import '../screens/ai_recommendation_screen.dart';
import '../screens/cart_screen.dart';
import '../screens/product_details.dart';
import '../screens/profile_screen.dart';
import '../screens/wishlist_screen.dart';
import '../widgets/banner_slider.dart';
import '../widgets/category_item.dart';
import '../widgets/product_card.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  final Color primaryColor = const Color(0xffFF3D5A);

  final TextEditingController searchController = TextEditingController();

  String selectedCategory = "All";
  String searchQuery = "";
  int currentIndex = 0;

  final List<Map<String, dynamic>> categories = [
    {"title": "All", "icon": Icons.apps},
    {"title": "Men", "icon": Icons.man},
    {"title": "Women", "icon": Icons.woman},
    {"title": "Shoes", "icon": Icons.shopping_bag},
    {"title": "Jackets", "icon": Icons.checkroom},
    {"title": "Accessories", "icon": Icons.watch},
    {"title": "Couple Sets", "icon": Icons.favorite},
  ];

  /// SAMPLE PRODUCTS
  /// Replace this list with your full 101 products
  final List<ProductModel> products = [
    ProductModel(
      id: "1", name: "Couple Hoodie",

      description: "Premium Gen Z matching hoodie",
      price: "LKR 14,500",
      image: "assets/images/1.jpg",
      category: "Couple Sets",
      rating: 4.8,
      reviews: 120,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "White"], isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false, ),
      ProductModel( id: "2",
      name: "Fashion Jacket",
      description: "Modern stylish Gen Z jacket",
      price: "LKR 22,000",
      image: "assets/images/2.jpg",
      category: "Jackets",
      rating: 4.7,
      reviews: 95,
      sizes: ["M", "L", "XL"],
      colors: ["Brown", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
      ),

      ProductModel(
      id: "3",
      name: "Modern Sneakers",
      description: "Comfortable trendy sneakers", 
      price: "LKR 17,500",
      image: "assets/images/3.jpg",
      category: "Shoes",
      rating: 4.9,
      reviews: 150,
      sizes: ["40", "41", "42", "43"],
      colors: ["White", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: true,
      ),

      ProductModel(
        id: "4",
      name: "Streetwear Outfit",
      description: "Oversized trendy fashion set", 
      price: "LKR 26,500",
      image: "assets/images/4.jpg",
      category: "Men",
      rating: 4.6, reviews: 88,
      sizes: ["S", "M", "L"],
      colors: ["Black", "Grey"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: false, ),
      ProductModel( id: "5",
      name: "Classic Black Hoodie",
      description: "Warm oversized street hoodie", 
      price: "LKR 13,500",
      image: "assets/images/5.jpg",
      category: "Men",
      rating: 4.7,
      reviews: 85,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "Grey"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
      ),

      ProductModel(
      id: "6",
      name: "Elegant Women Dress",
      description: "Beautiful modern dress for women", 
      price: "LKR 20,500", image: "assets/images/6.jpg", 
      category: "Women", rating: 4.9,
      reviews: 120,
      sizes: ["S", "M", "L"],
      colors: ["Red", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
      ),
      ProductModel( id: "7",
      name: "White Sneakers",
      description: "Comfortable casual sneakers",
      price: "LKR 16,000",
      image: "assets/images/7.jpg",
      category: "Shoes",
      rating: 4.8,
      reviews: 99,
      sizes: ["40", "41", "42", "43"],
      colors: ["White"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
      ),
      ProductModel(
      id: "8",
      name: "Denim Jacket",
      description: "Stylish blue denim jacket",
      price: "LKR 21,500",
      image: "assets/images/8.jpg",
      category: "Jackets",
      rating: 4.6, reviews: 65,
      sizes: ["M", "L", "XL"],
      colors: ["Blue"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: true,
      isFlashSale: false,
      ),
      ProductModel( id: "9",
      name: "Luxury Watch",
      description: "Modern stylish watch",
      price: "LKR 35,000",
      image: "assets/images/9.jpg",
      category: "Accessories",
      rating: 4.9, reviews: 200,
      sizes: ["Free"],
      colors: ["Black", "Silver"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
      ),
      
      ProductModel(
      id: "10",
      name: "Couple T-Shirt Set",
      description: "Matching outfit for couples",
      price: "LKR 17,000",
      image: "assets/images/10.jpg",
      category: "Couple Sets",
      rating: 4.8,
      reviews: 110,
      sizes: ["S", "M", "L", "XL"],
      colors: ["White", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true, ),

      ProductModel(
      id: "11",
      name: "Streetwear Cargo Pants",
      description: "Baggy cargo pants for Gen Z style",
      price: "LKR 15,500",
      image: "assets/images/11.jpg",
      category: "Men",
      rating: 4.5,
      reviews: 77,
      sizes: ["M", "L", "XL"],
      colors: ["Black", "Khaki"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false, ),

      ProductModel(
        id: "12",
      name: "Oversized Graphic Tee",
      description: "Trendy oversized t-shirt",
      price: "LKR 10,500",
      image: "assets/images/12.jpg",
      category: "Men",
      rating: 4.7,
      reviews: 98,
      sizes: ["S", "M", "L"],
      colors: ["White", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true, ),
      ProductModel( id: "13",
      name: "Streetwear Cargo Pants",
      description: "Baggy cargo pants for Gen Z style",
      price: "LKR 15,500",
      image: "assets/images/13.jpg",
      category: "Men", rating: 4.5,
      reviews: 77,
      sizes: ["M", "L", "XL"],
      colors: ["Black", "Khaki"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false, ),
      ProductModel( id: "14",
      name: "Slim Fit Jeans",
      description: "Comfortable stylish jeans",
      price: "LKR 14,000",
      image: "assets/images/14.jpg",
      category: "Men",
      rating: 4.6,
      reviews: 80,
      sizes: ["30", "32", "34"],
      colors: ["Blue", "Black"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: true,
      isFlashSale: false, ),
      ProductModel( id: "15",
      name: "Urban Hoodie",
      description: "Premium cotton hoodie",
      price: "LKR 18,000",
      image: "assets/images/15.jpg",
      category: "Men", rating: 4.9,
      reviews: 130,
      sizes: ["M", "L", "XL"],
      colors: ["Grey", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: true, ),
      ProductModel( id: "16",
      name: "Casual Polo Shirt",
      description: "Classic stylish polo",
      price: "LKR 11,500",
      image: "assets/images/16.jpg",
      category: "Men", rating: 4.4,
      reviews: 50,
      sizes: ["S", "M", "L"],
      colors: ["Blue", "White"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: false,
      isFlashSale: false, ),
      ProductModel( id: "17",
      name: "Floral Summer Dress",
      description: "Elegant floral outfit",
      price: "LKR 19,000",
      image: "assets/images/17.jpg",
      category: "Women",
      rating: 4.8,
      reviews: 140,
      sizes: ["S", "M", "L"],
      colors: ["Pink", "White"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false, ),
    ProductModel(
      id: "18",
      name: "Women Blazer",
      description: "Professional stylish blazer",
      price: "LKR 26,000",
      image: "assets/images/18.jpg",
      category: "Women",
      rating: 4.7,
      reviews: 92,
      sizes: ["M", "L"],
      colors: ["Black", "Cream"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "19",
      name: "Crop Top",
      description: "Fashionable crop top",
      price: "LKR 8,500",
      image: "assets/images/19.jpg",
      category: "Women",
      rating: 4.6,
      reviews: 73,
      sizes: ["S", "M", "L"],
      colors: ["White", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "20",
      name: "Stylish Handbag",
      description: "Luxury women handbag",
      price: "LKR 28,000",
      image: "assets/images/20.jpg",
      category: "Accessories",
      rating: 4.9,
      reviews: 160,
      sizes: ["Free"],
      colors: ["Brown", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "21",
      name: "Women Sneakers",
      description: "Comfortable stylish shoes",
      price: "LKR 18,500",
      image: "assets/images/21.jpg",
      category: "Shoes",
      rating: 4.8,
      reviews: 118,
      sizes: ["38", "39", "40"],
      colors: ["White", "Pink"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: true,
    ),

    /// MORE PRODUCTS - SRI LANKA PRICE VERSION
    ProductModel(
      id: "22",
      name: "Running Shoes",
      description: "High comfort running sneakers",
      price: "LKR 24,500",
      image: "assets/images/22.jpg",
      category: "Shoes",
      rating: 4.9,
      reviews: 210,
      sizes: ["40", "41", "42", "43"],
      colors: ["Black", "Blue"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "23",
      name: "Canvas Shoes",
      description: "Classic casual canvas shoes",
      price: "LKR 13,500",
      image: "assets/images/23.jpg",
      category: "Shoes",
      rating: 4.5,
      reviews: 66,
      sizes: ["39", "40", "41"],
      colors: ["White", "Black"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "24",
      name: "Leather Boots",
      description: "Premium leather boots",
      price: "LKR 32,000",
      image: "assets/images/24.jpg",
      category: "Shoes",
      rating: 4.8,
      reviews: 101,
      sizes: ["41", "42", "43"],
      colors: ["Brown", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: false,
    ),

    ProductModel(
      id: "25",
      name: "Sport Sneakers",
      description: "Lightweight training shoes",
      price: "LKR 21,000",
      image: "assets/images/25.jpg",
      category: "Shoes",
      rating: 4.7,
      reviews: 134,
      sizes: ["40", "41", "42"],
      colors: ["Red", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: true,
    ),

    ProductModel(
      id: "26",
      name: "Luxury Heels",
      description: "Elegant women heels",
      price: "LKR 27,500",
      image: "assets/images/26.jpg",
      category: "Shoes",
      rating: 4.8,
      reviews: 89,
      sizes: ["37", "38", "39"],
      colors: ["Black", "Gold"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: false,
    ),

    ProductModel(
      id: "27",
      name: "Winter Puffer Jacket",
      description: "Warm oversized winter jacket",
      price: "LKR 36,000",
      image: "assets/images/27.jpg",
      category: "Jackets",
      rating: 4.9,
      reviews: 188,
      sizes: ["M", "L", "XL"],
      colors: ["Black", "Navy"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "28",
      name: "Classic Leather Jacket",
      description: "Premium biker leather jacket",
      price: "LKR 45,000",
      image: "assets/images/28.jpg",
      category: "Jackets",
      rating: 4.8,
      reviews: 155,
      sizes: ["M", "L", "XL"],
      colors: ["Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "29",
      name: "Couple Matching Hoodies",
      description: "Cute matching hoodie set",
      price: "LKR 25,500",
      image: "assets/images/29.jpg",
      category: "Couple Sets",
      rating: 4.9,
      reviews: 240,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Pink", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: true,
    ),

    ProductModel(
      id: "30",
      name: "Smart Casual Shirt",
      description: "Stylish casual office shirt",
      price: "LKR 15,000",
      image: "assets/images/30.jpg",
      category: "Men",
      rating: 4.6,
      reviews: 72,
      sizes: ["M", "L", "XL"],
      colors: ["White", "Blue"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "31",
      name: "Women Long Coat",
      description: "Elegant winter long coat",
      price: "LKR 39,000",
      image: "assets/images/31.jpg",
      category: "Women",
      rating: 4.9,
      reviews: 170,
      sizes: ["S", "M", "L"],
      colors: ["Cream", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "32",
      name: "Minimalist Backpack",
      description: "Modern stylish backpack",
      price: "LKR 6,500",
      image: "assets/images/32.jpg",
      category: "Accessories",
      rating: 4.7,
      reviews: 115,
      sizes: ["Free"],
      colors: ["Black", "Grey"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "33",
      name: "Streetwear Joggers",
      description: "Comfortable urban joggers",
      price: "LKR 14,500",
      image: "assets/images/33.jpg",
      category: "Men",
      rating: 4.5,
      reviews: 60,
      sizes: ["S", "M", "L"],
      colors: ["Grey", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: false,
    ),

    ProductModel(
      id: "34",
      name: "Elegant Maxi Dress",
      description: "Beautiful evening maxi dress",
      price: "LKR 30,000",
      image: "assets/images/34.jpg",
      category: "Women",
      rating: 4.8,
      reviews: 143,
      sizes: ["S", "M", "L"],
      colors: ["Red", "Green"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: true,
    ),

    ProductModel(
      id: "35",
      name: "Luxury Sunglasses",
      description: "UV protected stylish glasses",
      price: "LKR 11,500",
      image: "assets/images/35.jpg",
      category: "Accessories",
      rating: 4.6,
      reviews: 90,
      sizes: ["Free"],
      colors: ["Black", "Brown"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "36",
      name: "Chunky Sneakers",
      description: "Gen Z trendy chunky shoes",
      price: "LKR 29,500",
      image: "assets/images/36.jpg",
      category: "Shoes",
      rating: 4.9,
      reviews: 199,
      sizes: ["40", "41", "42", "43"],
      colors: ["White", "Grey"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "37",
      name: "Couple Denim Jackets",
      description: "Matching denim jackets for couples",
      price: "LKR 42,000",
      image: "assets/images/37.jpg",
      category: "Couple Sets",
      rating: 4.8,
      reviews: 122,
      sizes: ["M", "L", "XL"],
      colors: ["Blue"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "38",
      name: "Beanie Hat",
      description: "Warm stylish winter beanie",
      price: "LKR 6,500",
      image: "assets/images/38.jpg",
      category: "Accessories",
      rating: 4.4,
      reviews: 48,
      sizes: ["Free"],
      colors: ["Black", "Grey"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "39",
      name: "Oversized Flannel Shirt",
      description: "Soft casual flannel shirt",
      price: "LKR 13,000",
      image: "assets/images/39.jpg",
      category: "Men",
      rating: 4.5,
      reviews: 80,
      sizes: ["M", "L", "XL"],
      colors: ["Red", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "40",
      name: "Women Crop Hoodie",
      description: "Fashionable cropped hoodie",
      price: "LKR 16,500",
      image: "assets/images/40.jpg",
      category: "Women",
      rating: 4.7,
      reviews: 108,
      sizes: ["S", "M", "L"],
      colors: ["Pink", "White"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "41",
      name: "Designer Belt",
      description: "Luxury leather fashion belt",
      price: "LKR 9,500",
      image: "assets/images/41.jpg",
      category: "Accessories",
      rating: 4.3,
      reviews: 39,
      sizes: ["M", "L"],
      colors: ["Brown", "Black"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "42",
      name: "Retro Sneakers",
      description: "Vintage inspired sneakers",
      price: "LKR 23,500",
      image: "assets/images/42.jpg",
      category: "Shoes",
      rating: 4.7,
      reviews: 127,
      sizes: ["40", "41", "42"],
      colors: ["White", "Blue"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "43",
      name: "Formal Suit Set",
      description: "Premium modern formal suit",
      price: "LKR 68,000",
      image: "assets/images/43.jpg",
      category: "Men",
      rating: 4.9,
      reviews: 95,
      sizes: ["M", "L", "XL"],
      colors: ["Black", "Navy"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "44",
      name: "Luxury Evening Gown",
      description: "Elegant party gown",
      price: "LKR 58,000",
      image: "assets/images/44.jpg",
      category: "Women",
      rating: 4.9,
      reviews: 210,
      sizes: ["S", "M", "L"],
      colors: ["Gold", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "45",
      name: "Sports Cap",
      description: "Adjustable casual cap",
      price: "LKR 5,500",
      image: "assets/images/45.jpg",
      category: "Accessories",
      rating: 4.2,
      reviews: 55,
      sizes: ["Free"],
      colors: ["Black", "White"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: true,
      isFlashSale: true,
    ),

    ProductModel(
      id: "46",
      name: "Running Shorts",
      description: "Comfortable lightweight shorts",
      price: "LKR 8,500",
      image: "assets/images/46.jpg",
      category: "Men",
      rating: 4.4,
      reviews: 64,
      sizes: ["S", "M", "L"],
      colors: ["Grey", "Black"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "47",
      name: "Urban Street Hoodie",
      description: "Trendy oversized hoodie for everyday wear",
      price: "LKR 18,500",
      image: "assets/images/47.jpg",
      category: "Men",
      rating: 4.8,
      reviews: 145,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "Grey"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "48",
      name: "Vintage Denim Jeans",
      description: "Classic relaxed fit denim jeans",
      price: "LKR 9,500",
      image: "assets/images/48.jpg",
      category: "Men",
      rating: 4.6,
      reviews: 98,
      sizes: ["30", "32", "34", "36"],
      colors: ["Blue", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "49",
      name: "Women Casual Blouse",
      description: "Elegant soft casual blouse",
      price: "LKR 12,500",
      image: "assets/images/49.jpg",
      category: "Women",
      rating: 4.7,
      reviews: 112,
      sizes: ["S", "M", "L"],
      colors: ["White", "Pink"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "50",
      name: "Classic High Heels",
      description: "Elegant high heels for parties",
      price: "LKR 6,500",
      image: "assets/images/50.jpg",
      category: "Shoes",
      rating: 4.9,
      reviews: 133,
      sizes: ["37", "38", "39", "40"],
      colors: ["Black", "Red"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "51",
      name: "Minimal Wrist Watch",
      description: "Luxury minimalist fashion watch",
      price: "LKR 6,000",
      image: "assets/images/51.jpg",
      category: "Accessories",
      rating: 4.9,
      reviews: 205,
      sizes: ["Free"],
      colors: ["Silver", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "52",
      name: "Couple Oversized T-Shirts",
      description: "Cute matching oversized tees",
      price: "LKR 18,000",
      image: "assets/images/52.jpg",
      category: "Couple Sets",
      rating: 4.8,
      reviews: 177,
      sizes: ["S", "M", "L", "XL"],
      colors: ["White", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: true,
    ),

    ProductModel(
      id: "53",
      name: "Casual Bomber Jacket",
      description: "Stylish lightweight bomber jacket",
      price: "LKR 9,500",
      image: "assets/images/53.jpg",
      category: "Jackets",
      rating: 4.7,
      reviews: 118,
      sizes: ["M", "L", "XL"],
      colors: ["Green", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "54",
      name: "Luxury Travel Bag",
      description: "Spacious premium travel backpack",
      price: "LKR 27,000",
      image: "assets/images/54.jpg",
      category: "Accessories",
      rating: 4.6,
      reviews: 74,
      sizes: ["Free"],
      colors: ["Brown", "Black"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "55",
      name: "Sport Running Shoes",
      description: "Comfortable shoes for daily running",
      price: "LKR 24,000",
      image: "assets/images/55.jpg",
      category: "Shoes",
      rating: 4.9,
      reviews: 198,
      sizes: ["40", "41", "42", "43"],
      colors: ["Blue", "White"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "56",
      name: "Women Long Skirt",
      description: "Elegant high waist long skirt",
      price: "LKR 14,500",
      image: "assets/images/56.jpg",
      category: "Women",
      rating: 4.5,
      reviews: 67,
      sizes: ["S", "M", "L"],
      colors: ["Black", "Cream"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "57",
      name: "Streetwear Cargo Jacket",
      description: "Modern oversized cargo jacket",
      price: "LKR 34,000",
      image: "assets/images/57.jpg",
      category: "Jackets",
      rating: 4.8,
      reviews: 123,
      sizes: ["M", "L", "XL"],
      colors: ["Khaki", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "58",
      name: "Luxury Gold Necklace",
      description: "Stylish premium necklace",
      price: "LKR 42,000",
      image: "assets/images/58.jpg",
      category: "Accessories",
      rating: 4.9,
      reviews: 166,
      sizes: ["Free"],
      colors: ["Gold"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "59",
      name: "Relaxed Fit Sweatpants",
      description: "Soft comfortable sweatpants",
      price: "LKR 13,500",
      image: "assets/images/59.jpg",
      category: "Men",
      rating: 4.4,
      reviews: 58,
      sizes: ["S", "M", "L"],
      colors: ["Grey", "Black"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "60",
      name: "Women Winter Sweater",
      description: "Warm knitted winter sweater",
      price: "LKR 16,500",
      image: "assets/images/60.jpg",
      category: "Women",
      rating: 4.7,
      reviews: 103,
      sizes: ["S", "M", "L"],
      colors: ["White", "Beige"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "61",
      name: "Couple Casual Outfit",
      description: "Matching casual streetwear set",
      price: "LKR 48,000",
      image: "assets/images/61.jpg",
      category: "Couple Sets",
      rating: 4.9,
      reviews: 221,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "White"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "62",
      name: "Retro Sunglasses",
      description: "Vintage style trendy sunglasses",
      price: "LKR 3,500",
      image: "assets/images/62.jpg",
      category: "Accessories",
      rating: 4.5,
      reviews: 69,
      sizes: ["Free"],
      colors: ["Black", "Brown"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: true,
      isFlashSale: true,
    ),

    ProductModel(
      id: "63",
      name: "Luxury Leather Boots",
      description: "Premium winter leather boots",
      price: "LKR 38,000",
      image: "assets/images/63.jpg",
      category: "Shoes",
      rating: 4.8,
      reviews: 144,
      sizes: ["41", "42", "43", "44"],
      colors: ["Brown", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: false,
    ),

    ProductModel(
      id: "64",
      name: "Oversized Knit Hoodie",
      description: "Soft knitted oversized hoodie",
      price: "LKR 20,500",
      image: "assets/images/64.jpg",
      category: "Men",
      rating: 4.6,
      reviews: 87,
      sizes: ["M", "L", "XL"],
      colors: ["Grey", "Brown"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "65",
      name: "Elegant Party Dress",
      description: "Beautiful luxury party dress",
      price: "LKR 44,000",
      image: "assets/images/65.jpg",
      category: "Women",
      rating: 4.9,
      reviews: 199,
      sizes: ["S", "M", "L"],
      colors: ["Red", "Gold"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: true,
    ),

    ProductModel(
      id: "66",
      name: "Minimal Crossbody Bag",
      description: "Stylish everyday crossbody bag",
      price: "LKR 16,000",
      image: "assets/images/66.jpg",
      category: "Accessories",
      rating: 4.6,
      reviews: 82,
      sizes: ["Free"],
      colors: ["Black", "Cream"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: false,
    ),

    ProductModel(
      id: "67",
      name: "Premium Varsity Jacket",
      description: "Classic varsity jacket with modern fit",
      price: "LKR 36,500",
      image: "assets/images/67.jpg",
      category: "Jackets",
      rating: 4.8,
      reviews: 176,
      sizes: ["M", "L", "XL"],
      colors: ["Black", "White"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "68",
      name: "Relaxed Fit Hoodie",
      description: "Soft cotton hoodie for daily wear",
      price: "LKR 16,500",
      image: "assets/images/68.jpg",
      category: "Men",
      rating: 4.5,
      reviews: 91,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Grey", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "69",
      name: "Women Office Blazer",
      description: "Elegant slim fit office blazer",
      price: "LKR 31,500",
      image: "assets/images/69.jpg",
      category: "Women",
      rating: 4.7,
      reviews: 138,
      sizes: ["S", "M", "L"],
      colors: ["Black", "Cream"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "70",
      name: "Canvas Street Sneakers",
      description: "Lightweight casual sneakers",
      price: "LKR 8,500",
      image: "assets/images/70.jpg",
      category: "Shoes",
      rating: 4.6,
      reviews: 120,
      sizes: ["39", "40", "41", "42"],
      colors: ["White", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "71",
      name: "Modern Smart Watch",
      description: "Stylish digital smartwatch",
      price: "LKR 46,000",
      image: "assets/images/71.jpg",
      category: "Accessories",
      rating: 4.9,
      reviews: 241,
      sizes: ["Free"],
      colors: ["Black", "Silver"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "72",
      name: "Couple Winter Hoodies",
      description: "Warm matching winter hoodie set",
      price: "LKR 29,000",
      image: "assets/images/72.jpg",
      category: "Couple Sets",
      rating: 4.8,
      reviews: 156,
      sizes: ["S", "M", "L", "XL"],
      colors: ["White", "Grey"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "73",
      name: "Slim Fit Trousers",
      description: "Modern slim fit formal trousers",
      price: "LKR 4,500",
      image: "assets/images/73.jpg",
      category: "Men",
      rating: 4.4,
      reviews: 74,
      sizes: ["30", "32", "34", "36"],
      colors: ["Black", "Navy"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "74",
      name: "Luxury Silk Dress",
      description: "Elegant silk evening dress",
      price: "LKR 55,000",
      image: "assets/images/74.jpg",
      category: "Women",
      rating: 4.9,
      reviews: 218,
      sizes: ["S", "M", "L"],
      colors: ["Red", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "75",
      name: "Leather Wallet",
      description: "Premium genuine leather wallet",
      price: "LKR 12,500",
      image: "assets/images/75.jpg",
      category: "Accessories",
      rating: 4.5,
      reviews: 81,
      sizes: ["Free"],
      colors: ["Brown", "Black"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "76",
      name: "High Top Sneakers",
      description: "Trendy high top street sneakers",
      price: "LKR 26,000",
      image: "assets/images/76.jpg",
      category: "Shoes",
      rating: 4.8,
      reviews: 166,
      sizes: ["40", "41", "42", "43"],
      colors: ["Black", "Red"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "77",
      name: "Classic Denim Jacket",
      description: "Vintage inspired denim jacket",
      price: "LKR 27,500",
      image: "assets/images/77.jpg",
      category: "Jackets",
      rating: 4.7,
      reviews: 112,
      sizes: ["M", "L", "XL"],
      colors: ["Blue"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "78",
      name: "Oversized Sweatshirt",
      description: "Comfortable oversized sweatshirt",
      price: "LKR 14,500",
      image: "assets/images/78.jpg",
      category: "Men",
      rating: 4.5,
      reviews: 92,
      sizes: ["S", "M", "L"],
      colors: ["Grey", "White"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "79",
      name: "Women Casual Cardigan",
      description: "Soft knitted casual cardigan",
      price: "LKR 18,500",
      image: "assets/images/79.jpg",
      category: "Women",
      rating: 4.6,
      reviews: 103,
      sizes: ["S", "M", "L"],
      colors: ["Cream", "Pink"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "80",
      name: "Luxury Bracelet",
      description: "Elegant fashion bracelet",
      price: "LKR 13,500",
      image: "assets/images/80.jpg",
      category: "Accessories",
      rating: 4.4,
      reviews: 69,
      sizes: ["Free"],
      colors: ["Gold", "Silver"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "81",
      name: "Sport Training Shoes",
      description: "Comfortable gym training shoes",
      price: "LKR 24,500",
      image: "assets/images/81.jpg",
      category: "Shoes",
      rating: 4.8,
      reviews: 187,
      sizes: ["40", "41", "42", "43"],
      colors: ["Blue", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: true,
    ),

    ProductModel(
      id: "82",
      name: "Street Style Cargo Pants",
      description: "Baggy cargo pants with modern style",
      price: "LKR 9,500",
      image: "assets/images/82.jpg",
      category: "Men",
      rating: 4.7,
      reviews: 132,
      sizes: ["M", "L", "XL"],
      colors: ["Khaki", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "83",
      name: "Elegant Women Handbag",
      description: "Luxury handbag with premium leather",
      price: "LKR 6,500",
      image: "assets/images/83.jpg",
      category: "Accessories",
      rating: 4.9,
      reviews: 204,
      sizes: ["Free"],
      colors: ["Brown", "Cream"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "84",
      name: "Urban Couple Tracksuit",
      description: "Matching tracksuit for couples",
      price: "LKR 48,500",
      image: "assets/images/84.jpg",
      category: "Couple Sets",
      rating: 4.8,
      reviews: 190,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "Grey"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "85",
      name: "Classic White Sneakers",
      description: "Minimalist everyday sneakers",
      price: "LKR 21,500",
      image: "assets/images/85.jpg",
      category: "Shoes",
      rating: 4.7,
      reviews: 144,
      sizes: ["39", "40", "41", "42"],
      colors: ["White"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "86",
      name: "Premium Wool Coat",
      description: "Elegant warm winter coat",
      price: "LKR 58,000",
      image: "assets/images/86.jpg",
      category: "Women",
      rating: 4.9,
      reviews: 176,
      sizes: ["S", "M", "L"],
      colors: ["Beige", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "87",
      name: "Casual Men Polo",
      description: "Comfortable cotton polo shirt",
      price: "LKR 10,500",
      image: "assets/images/87.jpg",
      category: "Men",
      rating: 4.4,
      reviews: 59,
      sizes: ["S", "M", "L"],
      colors: ["Blue", "White"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: true,
      isFlashSale: true,
    ),

    ProductModel(
      id: "88",
      name: "Luxury Earrings",
      description: "Elegant gold plated earrings",
      price: "LKR 15,500",
      image: "assets/images/88.jpg",
      category: "Accessories",
      rating: 4.6,
      reviews: 88,
      sizes: ["Free"],
      colors: ["Gold", "Silver"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: false,
    ),

    ProductModel(
      id: "89",
      name: "Chunky Running Sneakers",
      description: "Fashionable sporty sneakers",
      price: "LKR 29,500",
      image: "assets/images/89.jpg",
      category: "Shoes",
      rating: 4.8,
      reviews: 222,
      sizes: ["40", "41", "42", "43"],
      colors: ["White", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: true,
    ),

    ProductModel(
      id: "90",
      name: "Oversized Women Hoodie",
      description: "Soft oversized hoodie for women",
      price: "LKR 18,500",
      image: "assets/images/90.jpg",
      category: "Women",
      rating: 4.7,
      reviews: 121,
      sizes: ["S", "M", "L"],
      colors: ["Pink", "Grey"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: false,
    ),

    ProductModel(
      id: "91",
      name: "Modern Denim Shirt",
      description: "Stylish denim casual shirt",
      price: "LKR 16,500",
      image: "assets/images/91.jpg",
      category: "Men",
      rating: 4.5,
      reviews: 74,
      sizes: ["M", "L", "XL"],
      colors: ["Blue"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: true,
      isFlashSale: true,
    ),

    ProductModel(
      id: "92",
      name: "Minimal Leather Backpack",
      description: "Premium backpack for travel and work",
      price: "LKR 31,500",
      image: "assets/images/92.jpg",
      category: "Accessories",
      rating: 4.8,
      reviews: 136,
      sizes: ["Free"],
      colors: ["Black", "Brown"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "93",
      name: "Couple Matching Jackets",
      description: "Trendy matching jackets for couples",
      price: "LKR 16800",
      image: "assets/images/93.jpg",
      category: "Couple Sets",
      rating: 4.9,
      reviews: 207,
      sizes: ["M", "L", "XL"],
      colors: ["Blue", "Black"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "94",
      name: "Women Summer Top",
      description: "Lightweight stylish summer top",
      price: "LKR 9,500",
      image: "assets/images/94.jpg",
      category: "Women",
      rating: 4.5,
      reviews: 63,
      sizes: ["S", "M", "L"],
      colors: ["White", "Yellow"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "95",
      name: "Luxury Running Shoes",
      description: "Premium comfort running sneakers",
      price: "LKR 39,500",
      image: "assets/images/95.jpg",
      category: "Shoes",
      rating: 4.9,
      reviews: 255,
      sizes: ["40", "41", "42", "43", "44"],
      colors: ["Black", "Blue"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "96",
      name: "Casual Zip Hoodie",
      description: "Comfortable zip-up hoodie",
      price: "LKR 14,500",
      image: "assets/images/96.jpg",
      category: "Men",
      rating: 4.4,
      reviews: 81,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Grey", "Black"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "97",
      name: "Elegant Silk Scarf",
      description: "Luxury soft silk scarf",
      price: "LKR 8,000",
      image: "assets/images/97.jpg",
      category: "Accessories",
      rating: 4.3,
      reviews: 44,
      sizes: ["Free"],
      colors: ["Red", "Cream"],
      isFavorite: false,
      isTrending: false,
      isNewArrival: true,
      isFlashSale: true,
    ),

    ProductModel(
      id: "98",
      name: "Streetwear Jogger Set",
      description: "Matching hoodie and jogger set",
      price: "LKR 37,000",
      image: "assets/images/98.jpg",
      category: "Men",
      rating: 4.8,
      reviews: 173,
      sizes: ["M", "L", "XL"],
      colors: ["Black", "Grey"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: false,
    ),

    ProductModel(
      id: "99",
      name: "Women Elegant Heels",
      description: "Luxury high heels for special events",
      price: "LKR 33,000",
      image: "assets/images/99.jpg",
      category: "Shoes",
      rating: 4.8,
      reviews: 148,
      sizes: ["37", "38", "39", "40"],
      colors: ["Black", "Gold"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: true,
    ),

    ProductModel(
      id: "100",
      name: "Premium Aviator Sunglasses",
      description: "Modern UV protection sunglasses",
      price: "LKR 12,000",
      image: "assets/images/100.jpg",
      category: "Accessories",
      rating: 4.5,
      reviews: 72,
      sizes: ["Free"],
      colors: ["Black", "Brown"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: false,
      isFlashSale: false,
    ),

    ProductModel(
      id: "101",
      name: "Luxury Couple Outfit",
      description: "Premium matching fashion set",
      price: "LKR 12,000",
      image: "assets/images/101.jpg",
      category: "Couple Sets",
      rating: 4.9,
      reviews: 320,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "White"],
      isFavorite: false,
      isTrending: true,
      isNewArrival: true,
      isFlashSale: true,
    ),
  ];

  Future<void> refreshProducts() async {
    await Future.delayed(const Duration(milliseconds: 500));
    setState(() {});
  }

  List<ProductModel> get filteredProducts {
    return products.where((product) {
      final categoryMatch = selectedCategory == "All"
          ? true
          : product.category == selectedCategory;

      final searchMatch = product.name
          .toLowerCase()
          .contains(searchQuery.toLowerCase());

      return categoryMatch && searchMatch;
    }).toList();
  }

  @override
  void dispose() {
    searchController.dispose();
    super.dispose();
  }

  void navigateBottomBar(int index) {
    setState(() {
      currentIndex = index;
    });

    switch (index) {
      case 1:
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (_) => const WishlistScreen(),
          ),
        );
        break;

      case 2:
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (_) => CartScreen(),
          ),
        );
        break;

      case 3:
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (_) => const ProfileScreen(),
          ),
        );
        break;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,

      appBar: AppBar(
        elevation: 0,
        backgroundColor: Colors.white,

        title: const Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              "Hello 👋",
              style: TextStyle(
                color: Colors.grey,
                fontSize: 14,
              ),
            ),
            Text(
              "Mr & Mrs Gen Z Outfit",
              style: TextStyle(
                color: Colors.black,
                fontWeight: FontWeight.bold,
                fontSize: 22,
              ),
            ),
          ],
        ),

        actions: [
          IconButton(
            icon: Icon(
              Icons.auto_awesome,
              color: primaryColor,
            ),
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (_) => const AIRecommendationScreen(),
                ),
              );
            },
          ),
          IconButton(
            icon: const Icon(
              Icons.shopping_cart,
              color: Colors.black,
            ),
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (_) => CartScreen(),
                ),
              );
            },
          ),
        ],
      ),

      body: RefreshIndicator(
        onRefresh: refreshProducts,
        child: CustomScrollView(
          slivers: [
            SliverToBoxAdapter(
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Column(
                  children: [
                    TextField(
                      controller: searchController,
                      onChanged: (value) {
                        setState(() {
                          searchQuery = value;
                        });
                      },
                      decoration: InputDecoration(
                        hintText: "Search products...",
                        prefixIcon: const Icon(Icons.search),
                        filled: true,
                        fillColor: Colors.grey.shade100,
                        border: OutlineInputBorder(
                          borderRadius:
                              BorderRadius.circular(16),
                          borderSide: BorderSide.none,
                        ),
                      ),
                    ),

                    const SizedBox(height: 20),

                    const BannerSlider(),

                    const SizedBox(height: 25),

                    SizedBox(
                      height: 100,
                      child: ListView.builder(
                        scrollDirection: Axis.horizontal,
                        itemCount: categories.length,
                        itemBuilder: (context, index) {
                          return CategoryItem(
                            title: categories[index]["title"],
                            isSelected:
                                selectedCategory ==
                                    categories[index]["title"],
                            onTap: () {
                              setState(() {
                                selectedCategory =
                                    categories[index]["title"];
                              });
                            },
                          );
                        },
                      ),
                    ),
                  ],
                ),
              ),
            ),

            filteredProducts.isEmpty
                ? const SliverFillRemaining(
                    child: Center(
                      child: Text(
                        "No Products Found",
                      ),
                    ),
                  )
                : SliverPadding(
                    padding: const EdgeInsets.all(16),
                    sliver: SliverGrid(
                      delegate:
                          SliverChildBuilderDelegate(
                        (context, index) {
                          final product =
                              filteredProducts[index];

                          return ProductCard(
                            product: product,
                            onTap: () {
                              Navigator.push(
                                context,
                                MaterialPageRoute(
                                  builder: (_) =>
                                      ProductDetailsScreen(
                                    product: product,
                                  ),
                                ),
                              );
                            },
                          );
                        },
                        childCount:
                            filteredProducts.length,
                      ),
                      gridDelegate:
                          const SliverGridDelegateWithFixedCrossAxisCount(
                        crossAxisCount: 2,
                        crossAxisSpacing: 15,
                        mainAxisSpacing: 15,
                        childAspectRatio: 0.62,
                      ),
                    ),
                  ),
          ],
        ),
      ),

      bottomNavigationBar: BottomNavigationBar(
        currentIndex: currentIndex,
        selectedItemColor: primaryColor,
        type: BottomNavigationBarType.fixed,
        onTap: navigateBottomBar,
        items: const [
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: "Home",
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.favorite),
            label: "Wishlist",
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.shopping_cart),
            label: "Cart",
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.person),
            label: "Profile",
          ),
        ],
      ),
    );
  }
}